// Code generated by generate.go; DO NOT EDIT.

package packets

import (
	"github.com/zeozeozeo/minego/internal/data/versions/v1_21_11/packet_ids"
	jp "github.com/zeozeozeo/minego/internal/protocol/java_protocol"
	ns "github.com/zeozeozeo/minego/internal/protocol/java_protocol/net_structures"
)

func (p *C2SAcceptCodeOfConduct) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SAcceptCodeOfConductID)
}
func (p *C2SAcceptCodeOfConduct) State() jp.State { return jp.StateConfiguration }
func (p *C2SAcceptCodeOfConduct) Bound() jp.Bound { return jp.C2S }

func (p *C2SClientInformationConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SClientInformationConfigurationID)
}
func (p *C2SClientInformationConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *C2SClientInformationConfiguration) Bound() jp.Bound { return jp.C2S }

func (p *C2SCookieResponseConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SCookieResponseConfigurationID)
}
func (p *C2SCookieResponseConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *C2SCookieResponseConfiguration) Bound() jp.Bound { return jp.C2S }

func (p *C2SCustomClickActionConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SCustomClickActionConfigurationID)
}
func (p *C2SCustomClickActionConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *C2SCustomClickActionConfiguration) Bound() jp.Bound { return jp.C2S }

func (p *C2SCustomPayloadConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SCustomPayloadConfigurationID)
}
func (p *C2SCustomPayloadConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *C2SCustomPayloadConfiguration) Bound() jp.Bound { return jp.C2S }

func (p *C2SFinishConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SFinishConfigurationID)
}
func (p *C2SFinishConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *C2SFinishConfiguration) Bound() jp.Bound { return jp.C2S }

func (p *C2SKeepAliveConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SKeepAliveConfigurationID)
}
func (p *C2SKeepAliveConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *C2SKeepAliveConfiguration) Bound() jp.Bound { return jp.C2S }

func (p *C2SPongConfiguration) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPongConfigurationID) }
func (p *C2SPongConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *C2SPongConfiguration) Bound() jp.Bound { return jp.C2S }

func (p *C2SResourcePackConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SResourcePackConfigurationID)
}
func (p *C2SResourcePackConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *C2SResourcePackConfiguration) Bound() jp.Bound { return jp.C2S }

func (p *C2SSelectKnownPacks) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSelectKnownPacksID) }
func (p *C2SSelectKnownPacks) State() jp.State { return jp.StateConfiguration }
func (p *C2SSelectKnownPacks) Bound() jp.Bound { return jp.C2S }

func (p *S2CClearDialogConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CClearDialogConfigurationID)
}
func (p *S2CClearDialogConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CClearDialogConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CCodeOfConduct) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CCodeOfConductID) }
func (p *S2CCodeOfConduct) State() jp.State { return jp.StateConfiguration }
func (p *S2CCodeOfConduct) Bound() jp.Bound { return jp.S2C }

func (p *S2CCookieRequestConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CCookieRequestConfigurationID)
}
func (p *S2CCookieRequestConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CCookieRequestConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CCustomPayloadConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CCustomPayloadConfigurationID)
}
func (p *S2CCustomPayloadConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CCustomPayloadConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CCustomReportDetailsConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CCustomReportDetailsConfigurationID)
}
func (p *S2CCustomReportDetailsConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CCustomReportDetailsConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CDisconnectConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CDisconnectConfigurationID)
}
func (p *S2CDisconnectConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CDisconnectConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CFinishConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CFinishConfigurationID)
}
func (p *S2CFinishConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CFinishConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CKeepAliveConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CKeepAliveConfigurationID)
}
func (p *S2CKeepAliveConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CKeepAliveConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CPingConfiguration) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPingConfigurationID) }
func (p *S2CPingConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CPingConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CRegistryData) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CRegistryDataID) }
func (p *S2CRegistryData) State() jp.State { return jp.StateConfiguration }
func (p *S2CRegistryData) Bound() jp.Bound { return jp.S2C }

func (p *S2CResetChat) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CResetChatID) }
func (p *S2CResetChat) State() jp.State { return jp.StateConfiguration }
func (p *S2CResetChat) Bound() jp.Bound { return jp.S2C }

func (p *S2CResourcePackPopConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CResourcePackPopConfigurationID)
}
func (p *S2CResourcePackPopConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CResourcePackPopConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CResourcePackPushConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CResourcePackPushConfigurationID)
}
func (p *S2CResourcePackPushConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CResourcePackPushConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CSelectKnownPacks) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSelectKnownPacksID) }
func (p *S2CSelectKnownPacks) State() jp.State { return jp.StateConfiguration }
func (p *S2CSelectKnownPacks) Bound() jp.Bound { return jp.S2C }

func (p *S2CServerLinksConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CServerLinksConfigurationID)
}
func (p *S2CServerLinksConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CServerLinksConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CShowDialogConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CShowDialogConfigurationID)
}
func (p *S2CShowDialogConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CShowDialogConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CStoreCookieConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CStoreCookieConfigurationID)
}
func (p *S2CStoreCookieConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CStoreCookieConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CTransferConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CTransferConfigurationID)
}
func (p *S2CTransferConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CTransferConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CUpdateEnabledFeatures) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CUpdateEnabledFeaturesID)
}
func (p *S2CUpdateEnabledFeatures) State() jp.State { return jp.StateConfiguration }
func (p *S2CUpdateEnabledFeatures) Bound() jp.Bound { return jp.S2C }

func (p *S2CUpdateTagsConfiguration) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CUpdateTagsConfigurationID)
}
func (p *S2CUpdateTagsConfiguration) State() jp.State { return jp.StateConfiguration }
func (p *S2CUpdateTagsConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *C2SIntention) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SIntentionID) }
func (p *C2SIntention) State() jp.State { return jp.StateHandshake }
func (p *C2SIntention) Bound() jp.Bound { return jp.C2S }

func (p *C2SCookieResponseLogin) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SCookieResponseLoginID)
}
func (p *C2SCookieResponseLogin) State() jp.State { return jp.StateLogin }
func (p *C2SCookieResponseLogin) Bound() jp.Bound { return jp.C2S }

func (p *C2SCustomQueryAnswer) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SCustomQueryAnswerID) }
func (p *C2SCustomQueryAnswer) State() jp.State { return jp.StateLogin }
func (p *C2SCustomQueryAnswer) Bound() jp.Bound { return jp.C2S }

func (p *C2SHello) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SHelloID) }
func (p *C2SHello) State() jp.State { return jp.StateLogin }
func (p *C2SHello) Bound() jp.Bound { return jp.C2S }

func (p *C2SKey) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SKeyID) }
func (p *C2SKey) State() jp.State { return jp.StateLogin }
func (p *C2SKey) Bound() jp.Bound { return jp.C2S }

func (p *C2SLoginAcknowledged) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SLoginAcknowledgedID) }
func (p *C2SLoginAcknowledged) State() jp.State { return jp.StateLogin }
func (p *C2SLoginAcknowledged) Bound() jp.Bound { return jp.C2S }

func (p *S2CCookieRequestLogin) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CCookieRequestLoginID) }
func (p *S2CCookieRequestLogin) State() jp.State { return jp.StateLogin }
func (p *S2CCookieRequestLogin) Bound() jp.Bound { return jp.S2C }

func (p *S2CCustomQuery) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CCustomQueryID) }
func (p *S2CCustomQuery) State() jp.State { return jp.StateLogin }
func (p *S2CCustomQuery) Bound() jp.Bound { return jp.S2C }

func (p *S2CHello) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CHelloID) }
func (p *S2CHello) State() jp.State { return jp.StateLogin }
func (p *S2CHello) Bound() jp.Bound { return jp.S2C }

func (p *S2CLoginCompression) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CLoginCompressionID) }
func (p *S2CLoginCompression) State() jp.State { return jp.StateLogin }
func (p *S2CLoginCompression) Bound() jp.Bound { return jp.S2C }

func (p *S2CLoginDisconnectLogin) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CLoginDisconnectID) }
func (p *S2CLoginDisconnectLogin) State() jp.State { return jp.StateLogin }
func (p *S2CLoginDisconnectLogin) Bound() jp.Bound { return jp.S2C }

func (p *S2CLoginFinished) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CLoginFinishedID) }
func (p *S2CLoginFinished) State() jp.State { return jp.StateLogin }
func (p *S2CLoginFinished) Bound() jp.Bound { return jp.S2C }

func (p *C2SAcceptTeleportation) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SAcceptTeleportationID)
}
func (p *C2SAcceptTeleportation) State() jp.State { return jp.StatePlay }
func (p *C2SAcceptTeleportation) Bound() jp.Bound { return jp.C2S }

func (p *C2SBlockEntityTagQuery) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SBlockEntityTagQueryID)
}
func (p *C2SBlockEntityTagQuery) State() jp.State { return jp.StatePlay }
func (p *C2SBlockEntityTagQuery) Bound() jp.Bound { return jp.C2S }

func (p *C2SBundleItemSelected) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SBundleItemSelectedID) }
func (p *C2SBundleItemSelected) State() jp.State { return jp.StatePlay }
func (p *C2SBundleItemSelected) Bound() jp.Bound { return jp.C2S }

func (p *C2SChangeDifficulty) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SChangeDifficultyID) }
func (p *C2SChangeDifficulty) State() jp.State { return jp.StatePlay }
func (p *C2SChangeDifficulty) Bound() jp.Bound { return jp.C2S }

func (p *C2SChangeGameMode) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SChangeGameModeID) }
func (p *C2SChangeGameMode) State() jp.State { return jp.StatePlay }
func (p *C2SChangeGameMode) Bound() jp.Bound { return jp.C2S }

func (p *C2SChat) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SChatID) }
func (p *C2SChat) State() jp.State { return jp.StatePlay }
func (p *C2SChat) Bound() jp.Bound { return jp.C2S }

func (p *C2SChatAck) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SChatAckID) }
func (p *C2SChatAck) State() jp.State { return jp.StatePlay }
func (p *C2SChatAck) Bound() jp.Bound { return jp.C2S }

func (p *C2SChatCommand) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SChatCommandID) }
func (p *C2SChatCommand) State() jp.State { return jp.StatePlay }
func (p *C2SChatCommand) Bound() jp.Bound { return jp.C2S }

func (p *C2SChatCommandSigned) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SChatCommandSignedID) }
func (p *C2SChatCommandSigned) State() jp.State { return jp.StatePlay }
func (p *C2SChatCommandSigned) Bound() jp.Bound { return jp.C2S }

func (p *C2SChatSessionUpdate) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SChatSessionUpdateID) }
func (p *C2SChatSessionUpdate) State() jp.State { return jp.StatePlay }
func (p *C2SChatSessionUpdate) Bound() jp.Bound { return jp.C2S }

func (p *C2SChunkBatchReceived) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SChunkBatchReceivedID) }
func (p *C2SChunkBatchReceived) State() jp.State { return jp.StatePlay }
func (p *C2SChunkBatchReceived) Bound() jp.Bound { return jp.C2S }

func (p *C2SClientCommand) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SClientCommandID) }
func (p *C2SClientCommand) State() jp.State { return jp.StatePlay }
func (p *C2SClientCommand) Bound() jp.Bound { return jp.C2S }

func (p *C2SClientInformationPlay) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SClientInformationPlayID)
}
func (p *C2SClientInformationPlay) State() jp.State { return jp.StatePlay }
func (p *C2SClientInformationPlay) Bound() jp.Bound { return jp.C2S }

func (p *C2SClientTickEnd) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SClientTickEndID) }
func (p *C2SClientTickEnd) State() jp.State { return jp.StatePlay }
func (p *C2SClientTickEnd) Bound() jp.Bound { return jp.C2S }

func (p *C2SCommandSuggestion) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SCommandSuggestionID) }
func (p *C2SCommandSuggestion) State() jp.State { return jp.StatePlay }
func (p *C2SCommandSuggestion) Bound() jp.Bound { return jp.C2S }

func (p *C2SConfigurationAcknowledged) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SConfigurationAcknowledgedID)
}
func (p *C2SConfigurationAcknowledged) State() jp.State { return jp.StatePlay }
func (p *C2SConfigurationAcknowledged) Bound() jp.Bound { return jp.C2S }

func (p *C2SContainerButtonClick) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SContainerButtonClickID)
}
func (p *C2SContainerButtonClick) State() jp.State { return jp.StatePlay }
func (p *C2SContainerButtonClick) Bound() jp.Bound { return jp.C2S }

func (p *C2SContainerClick) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SContainerClickID) }
func (p *C2SContainerClick) State() jp.State { return jp.StatePlay }
func (p *C2SContainerClick) Bound() jp.Bound { return jp.C2S }

func (p *C2SContainerClose) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SContainerCloseID) }
func (p *C2SContainerClose) State() jp.State { return jp.StatePlay }
func (p *C2SContainerClose) Bound() jp.Bound { return jp.C2S }

func (p *C2SContainerSlotStateChanged) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SContainerSlotStateChangedID)
}
func (p *C2SContainerSlotStateChanged) State() jp.State { return jp.StatePlay }
func (p *C2SContainerSlotStateChanged) Bound() jp.Bound { return jp.C2S }

func (p *C2SCookieResponsePlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SCookieResponsePlayID) }
func (p *C2SCookieResponsePlay) State() jp.State { return jp.StatePlay }
func (p *C2SCookieResponsePlay) Bound() jp.Bound { return jp.C2S }

func (p *C2SCustomClickActionPlay) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SCustomClickActionPlayID)
}
func (p *C2SCustomClickActionPlay) State() jp.State { return jp.StatePlay }
func (p *C2SCustomClickActionPlay) Bound() jp.Bound { return jp.C2S }

func (p *C2SCustomPayloadPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SCustomPayloadPlayID) }
func (p *C2SCustomPayloadPlay) State() jp.State { return jp.StatePlay }
func (p *C2SCustomPayloadPlay) Bound() jp.Bound { return jp.C2S }

func (p *C2SDebugSubscriptionRequest) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SDebugSubscriptionRequestID)
}
func (p *C2SDebugSubscriptionRequest) State() jp.State { return jp.StatePlay }
func (p *C2SDebugSubscriptionRequest) Bound() jp.Bound { return jp.C2S }

func (p *C2SEditBook) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SEditBookID) }
func (p *C2SEditBook) State() jp.State { return jp.StatePlay }
func (p *C2SEditBook) Bound() jp.Bound { return jp.C2S }

func (p *C2SEntityTagQuery) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SEntityTagQueryID) }
func (p *C2SEntityTagQuery) State() jp.State { return jp.StatePlay }
func (p *C2SEntityTagQuery) Bound() jp.Bound { return jp.C2S }

func (p *C2SInteract) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SInteractID) }
func (p *C2SInteract) State() jp.State { return jp.StatePlay }
func (p *C2SInteract) Bound() jp.Bound { return jp.C2S }

func (p *C2SJigsawGenerate) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SJigsawGenerateID) }
func (p *C2SJigsawGenerate) State() jp.State { return jp.StatePlay }
func (p *C2SJigsawGenerate) Bound() jp.Bound { return jp.C2S }

func (p *C2SKeepAlivePlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SKeepAlivePlayID) }
func (p *C2SKeepAlivePlay) State() jp.State { return jp.StatePlay }
func (p *C2SKeepAlivePlay) Bound() jp.Bound { return jp.C2S }

func (p *C2SLockDifficulty) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SLockDifficultyID) }
func (p *C2SLockDifficulty) State() jp.State { return jp.StatePlay }
func (p *C2SLockDifficulty) Bound() jp.Bound { return jp.C2S }

func (p *C2SMovePlayerPos) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SMovePlayerPosID) }
func (p *C2SMovePlayerPos) State() jp.State { return jp.StatePlay }
func (p *C2SMovePlayerPos) Bound() jp.Bound { return jp.C2S }

func (p *C2SMovePlayerPosRot) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SMovePlayerPosRotID) }
func (p *C2SMovePlayerPosRot) State() jp.State { return jp.StatePlay }
func (p *C2SMovePlayerPosRot) Bound() jp.Bound { return jp.C2S }

func (p *C2SMovePlayerRot) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SMovePlayerRotID) }
func (p *C2SMovePlayerRot) State() jp.State { return jp.StatePlay }
func (p *C2SMovePlayerRot) Bound() jp.Bound { return jp.C2S }

func (p *C2SMovePlayerStatusOnly) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SMovePlayerStatusOnlyID)
}
func (p *C2SMovePlayerStatusOnly) State() jp.State { return jp.StatePlay }
func (p *C2SMovePlayerStatusOnly) Bound() jp.Bound { return jp.C2S }

func (p *C2SMoveVehicle) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SMoveVehicleID) }
func (p *C2SMoveVehicle) State() jp.State { return jp.StatePlay }
func (p *C2SMoveVehicle) Bound() jp.Bound { return jp.C2S }

func (p *C2SPaddleBoat) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPaddleBoatID) }
func (p *C2SPaddleBoat) State() jp.State { return jp.StatePlay }
func (p *C2SPaddleBoat) Bound() jp.Bound { return jp.C2S }

func (p *C2SPickItemFromBlock) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPickItemFromBlockID) }
func (p *C2SPickItemFromBlock) State() jp.State { return jp.StatePlay }
func (p *C2SPickItemFromBlock) Bound() jp.Bound { return jp.C2S }

func (p *C2SPickItemFromEntity) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPickItemFromEntityID) }
func (p *C2SPickItemFromEntity) State() jp.State { return jp.StatePlay }
func (p *C2SPickItemFromEntity) Bound() jp.Bound { return jp.C2S }

func (p *C2SPingRequestPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPingRequestPlayID) }
func (p *C2SPingRequestPlay) State() jp.State { return jp.StatePlay }
func (p *C2SPingRequestPlay) Bound() jp.Bound { return jp.C2S }

func (p *C2SPlaceRecipe) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPlaceRecipeID) }
func (p *C2SPlaceRecipe) State() jp.State { return jp.StatePlay }
func (p *C2SPlaceRecipe) Bound() jp.Bound { return jp.C2S }

func (p *C2SPlayerAbilities) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPlayerAbilitiesID) }
func (p *C2SPlayerAbilities) State() jp.State { return jp.StatePlay }
func (p *C2SPlayerAbilities) Bound() jp.Bound { return jp.C2S }

func (p *C2SPlayerAction) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPlayerActionID) }
func (p *C2SPlayerAction) State() jp.State { return jp.StatePlay }
func (p *C2SPlayerAction) Bound() jp.Bound { return jp.C2S }

func (p *C2SPlayerCommand) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPlayerCommandID) }
func (p *C2SPlayerCommand) State() jp.State { return jp.StatePlay }
func (p *C2SPlayerCommand) Bound() jp.Bound { return jp.C2S }

func (p *C2SPlayerInput) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPlayerInputID) }
func (p *C2SPlayerInput) State() jp.State { return jp.StatePlay }
func (p *C2SPlayerInput) Bound() jp.Bound { return jp.C2S }

func (p *C2SPlayerLoaded) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPlayerLoadedID) }
func (p *C2SPlayerLoaded) State() jp.State { return jp.StatePlay }
func (p *C2SPlayerLoaded) Bound() jp.Bound { return jp.C2S }

func (p *C2SPongPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPongPlayID) }
func (p *C2SPongPlay) State() jp.State { return jp.StatePlay }
func (p *C2SPongPlay) Bound() jp.Bound { return jp.C2S }

func (p *C2SRecipeBookChangeSettings) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SRecipeBookChangeSettingsID)
}
func (p *C2SRecipeBookChangeSettings) State() jp.State { return jp.StatePlay }
func (p *C2SRecipeBookChangeSettings) Bound() jp.Bound { return jp.C2S }

func (p *C2SRecipeBookSeenRecipe) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SRecipeBookSeenRecipeID)
}
func (p *C2SRecipeBookSeenRecipe) State() jp.State { return jp.StatePlay }
func (p *C2SRecipeBookSeenRecipe) Bound() jp.Bound { return jp.C2S }

func (p *C2SRenameItem) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SRenameItemID) }
func (p *C2SRenameItem) State() jp.State { return jp.StatePlay }
func (p *C2SRenameItem) Bound() jp.Bound { return jp.C2S }

func (p *C2SResourcePackPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SResourcePackPlayID) }
func (p *C2SResourcePackPlay) State() jp.State { return jp.StatePlay }
func (p *C2SResourcePackPlay) Bound() jp.Bound { return jp.C2S }

func (p *C2SSeenAdvancements) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSeenAdvancementsID) }
func (p *C2SSeenAdvancements) State() jp.State { return jp.StatePlay }
func (p *C2SSeenAdvancements) Bound() jp.Bound { return jp.C2S }

func (p *C2SSelectTrade) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSelectTradeID) }
func (p *C2SSelectTrade) State() jp.State { return jp.StatePlay }
func (p *C2SSelectTrade) Bound() jp.Bound { return jp.C2S }

func (p *C2SSetBeacon) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSetBeaconID) }
func (p *C2SSetBeacon) State() jp.State { return jp.StatePlay }
func (p *C2SSetBeacon) Bound() jp.Bound { return jp.C2S }

func (p *C2SSetCarriedItem) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSetCarriedItemID) }
func (p *C2SSetCarriedItem) State() jp.State { return jp.StatePlay }
func (p *C2SSetCarriedItem) Bound() jp.Bound { return jp.C2S }

func (p *C2SSetCommandBlock) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSetCommandBlockID) }
func (p *C2SSetCommandBlock) State() jp.State { return jp.StatePlay }
func (p *C2SSetCommandBlock) Bound() jp.Bound { return jp.C2S }

func (p *C2SSetCommandMinecart) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSetCommandMinecartID) }
func (p *C2SSetCommandMinecart) State() jp.State { return jp.StatePlay }
func (p *C2SSetCommandMinecart) Bound() jp.Bound { return jp.C2S }

func (p *C2SSetCreativeModeSlot) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2SSetCreativeModeSlotID)
}
func (p *C2SSetCreativeModeSlot) State() jp.State { return jp.StatePlay }
func (p *C2SSetCreativeModeSlot) Bound() jp.Bound { return jp.C2S }

func (p *C2SSetJigsawBlock) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSetJigsawBlockID) }
func (p *C2SSetJigsawBlock) State() jp.State { return jp.StatePlay }
func (p *C2SSetJigsawBlock) Bound() jp.Bound { return jp.C2S }

func (p *C2SSetStructureBlock) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSetStructureBlockID) }
func (p *C2SSetStructureBlock) State() jp.State { return jp.StatePlay }
func (p *C2SSetStructureBlock) Bound() jp.Bound { return jp.C2S }

func (p *C2SSetTestBlock) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSetTestBlockID) }
func (p *C2SSetTestBlock) State() jp.State { return jp.StatePlay }
func (p *C2SSetTestBlock) Bound() jp.Bound { return jp.C2S }

func (p *C2SSignUpdate) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSignUpdateID) }
func (p *C2SSignUpdate) State() jp.State { return jp.StatePlay }
func (p *C2SSignUpdate) Bound() jp.Bound { return jp.C2S }

func (p *C2SSwing) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SSwingID) }
func (p *C2SSwing) State() jp.State { return jp.StatePlay }
func (p *C2SSwing) Bound() jp.Bound { return jp.C2S }

func (p *C2STeleportToEntity) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2STeleportToEntityID) }
func (p *C2STeleportToEntity) State() jp.State { return jp.StatePlay }
func (p *C2STeleportToEntity) Bound() jp.Bound { return jp.C2S }

func (p *C2STestInstanceBlockAction) ID() ns.VarInt {
	return ns.VarInt(packet_ids.C2STestInstanceBlockActionID)
}
func (p *C2STestInstanceBlockAction) State() jp.State { return jp.StatePlay }
func (p *C2STestInstanceBlockAction) Bound() jp.Bound { return jp.C2S }

func (p *C2SUseItem) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SUseItemID) }
func (p *C2SUseItem) State() jp.State { return jp.StatePlay }
func (p *C2SUseItem) Bound() jp.Bound { return jp.C2S }

func (p *C2SUseItemOn) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SUseItemOnID) }
func (p *C2SUseItemOn) State() jp.State { return jp.StatePlay }
func (p *C2SUseItemOn) Bound() jp.Bound { return jp.C2S }

func (p *S2CAddEntity) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CAddEntityID) }
func (p *S2CAddEntity) State() jp.State { return jp.StatePlay }
func (p *S2CAddEntity) Bound() jp.Bound { return jp.S2C }

func (p *S2CAnimate) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CAnimateID) }
func (p *S2CAnimate) State() jp.State { return jp.StatePlay }
func (p *S2CAnimate) Bound() jp.Bound { return jp.S2C }

func (p *S2CAwardStats) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CAwardStatsID) }
func (p *S2CAwardStats) State() jp.State { return jp.StatePlay }
func (p *S2CAwardStats) Bound() jp.Bound { return jp.S2C }

func (p *S2CBlockChangedAck) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CBlockChangedAckID) }
func (p *S2CBlockChangedAck) State() jp.State { return jp.StatePlay }
func (p *S2CBlockChangedAck) Bound() jp.Bound { return jp.S2C }

func (p *S2CBlockDestruction) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CBlockDestructionID) }
func (p *S2CBlockDestruction) State() jp.State { return jp.StatePlay }
func (p *S2CBlockDestruction) Bound() jp.Bound { return jp.S2C }

func (p *S2CBlockEntityData) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CBlockEntityDataID) }
func (p *S2CBlockEntityData) State() jp.State { return jp.StatePlay }
func (p *S2CBlockEntityData) Bound() jp.Bound { return jp.S2C }

func (p *S2CBlockEvent) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CBlockEventID) }
func (p *S2CBlockEvent) State() jp.State { return jp.StatePlay }
func (p *S2CBlockEvent) Bound() jp.Bound { return jp.S2C }

func (p *S2CBlockUpdate) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CBlockUpdateID) }
func (p *S2CBlockUpdate) State() jp.State { return jp.StatePlay }
func (p *S2CBlockUpdate) Bound() jp.Bound { return jp.S2C }

func (p *S2CBossEvent) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CBossEventID) }
func (p *S2CBossEvent) State() jp.State { return jp.StatePlay }
func (p *S2CBossEvent) Bound() jp.Bound { return jp.S2C }

func (p *S2CBundleDelimiter) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CBundleDelimiterID) }
func (p *S2CBundleDelimiter) State() jp.State { return jp.StatePlay }
func (p *S2CBundleDelimiter) Bound() jp.Bound { return jp.S2C }

func (p *S2CChangeDifficulty) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CChangeDifficultyID) }
func (p *S2CChangeDifficulty) State() jp.State { return jp.StatePlay }
func (p *S2CChangeDifficulty) Bound() jp.Bound { return jp.S2C }

func (p *S2CChunkBatchFinished) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CChunkBatchFinishedID) }
func (p *S2CChunkBatchFinished) State() jp.State { return jp.StatePlay }
func (p *S2CChunkBatchFinished) Bound() jp.Bound { return jp.S2C }

func (p *S2CChunkBatchStart) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CChunkBatchStartID) }
func (p *S2CChunkBatchStart) State() jp.State { return jp.StatePlay }
func (p *S2CChunkBatchStart) Bound() jp.Bound { return jp.S2C }

func (p *S2CChunksBiomes) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CChunksBiomesID) }
func (p *S2CChunksBiomes) State() jp.State { return jp.StatePlay }
func (p *S2CChunksBiomes) Bound() jp.Bound { return jp.S2C }

func (p *S2CClearDialogPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CClearDialogPlayID) }
func (p *S2CClearDialogPlay) State() jp.State { return jp.StatePlay }
func (p *S2CClearDialogPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CClearTitles) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CClearTitlesID) }
func (p *S2CClearTitles) State() jp.State { return jp.StatePlay }
func (p *S2CClearTitles) Bound() jp.Bound { return jp.S2C }

func (p *S2CCommandSuggestions) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CCommandSuggestionsID) }
func (p *S2CCommandSuggestions) State() jp.State { return jp.StatePlay }
func (p *S2CCommandSuggestions) Bound() jp.Bound { return jp.S2C }

func (p *S2CCommands) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CCommandsID) }
func (p *S2CCommands) State() jp.State { return jp.StatePlay }
func (p *S2CCommands) Bound() jp.Bound { return jp.S2C }

func (p *S2CContainerClose) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CContainerCloseID) }
func (p *S2CContainerClose) State() jp.State { return jp.StatePlay }
func (p *S2CContainerClose) Bound() jp.Bound { return jp.S2C }

func (p *S2CContainerSetContent) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CContainerSetContentID)
}
func (p *S2CContainerSetContent) State() jp.State { return jp.StatePlay }
func (p *S2CContainerSetContent) Bound() jp.Bound { return jp.S2C }

func (p *S2CContainerSetData) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CContainerSetDataID) }
func (p *S2CContainerSetData) State() jp.State { return jp.StatePlay }
func (p *S2CContainerSetData) Bound() jp.Bound { return jp.S2C }

func (p *S2CContainerSetSlot) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CContainerSetSlotID) }
func (p *S2CContainerSetSlot) State() jp.State { return jp.StatePlay }
func (p *S2CContainerSetSlot) Bound() jp.Bound { return jp.S2C }

func (p *S2CCookieRequestPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CCookieRequestPlayID) }
func (p *S2CCookieRequestPlay) State() jp.State { return jp.StatePlay }
func (p *S2CCookieRequestPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CCooldown) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CCooldownID) }
func (p *S2CCooldown) State() jp.State { return jp.StatePlay }
func (p *S2CCooldown) Bound() jp.Bound { return jp.S2C }

func (p *S2CCustomChatCompletions) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CCustomChatCompletionsID)
}
func (p *S2CCustomChatCompletions) State() jp.State { return jp.StatePlay }
func (p *S2CCustomChatCompletions) Bound() jp.Bound { return jp.S2C }

func (p *S2CCustomPayloadPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CCustomPayloadPlayID) }
func (p *S2CCustomPayloadPlay) State() jp.State { return jp.StatePlay }
func (p *S2CCustomPayloadPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CCustomReportDetailsPlay) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CCustomReportDetailsPlayID)
}
func (p *S2CCustomReportDetailsPlay) State() jp.State { return jp.StatePlay }
func (p *S2CCustomReportDetailsPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CDamageEvent) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CDamageEventID) }
func (p *S2CDamageEvent) State() jp.State { return jp.StatePlay }
func (p *S2CDamageEvent) Bound() jp.Bound { return jp.S2C }

func (p *S2CDebugBlockValue) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CDebugBlockValueID) }
func (p *S2CDebugBlockValue) State() jp.State { return jp.StatePlay }
func (p *S2CDebugBlockValue) Bound() jp.Bound { return jp.S2C }

func (p *S2CDebugChunkValue) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CDebugChunkValueID) }
func (p *S2CDebugChunkValue) State() jp.State { return jp.StatePlay }
func (p *S2CDebugChunkValue) Bound() jp.Bound { return jp.S2C }

func (p *S2CDebugEntityValue) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CDebugEntityValueID) }
func (p *S2CDebugEntityValue) State() jp.State { return jp.StatePlay }
func (p *S2CDebugEntityValue) Bound() jp.Bound { return jp.S2C }

func (p *S2CDebugEvent) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CDebugEventID) }
func (p *S2CDebugEvent) State() jp.State { return jp.StatePlay }
func (p *S2CDebugEvent) Bound() jp.Bound { return jp.S2C }

func (p *S2CDebugSample) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CDebugSampleID) }
func (p *S2CDebugSample) State() jp.State { return jp.StatePlay }
func (p *S2CDebugSample) Bound() jp.Bound { return jp.S2C }

func (p *S2CDeleteChat) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CDeleteChatID) }
func (p *S2CDeleteChat) State() jp.State { return jp.StatePlay }
func (p *S2CDeleteChat) Bound() jp.Bound { return jp.S2C }

func (p *S2CDisconnectPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CDisconnectPlayID) }
func (p *S2CDisconnectPlay) State() jp.State { return jp.StatePlay }
func (p *S2CDisconnectPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CDisguisedChat) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CDisguisedChatID) }
func (p *S2CDisguisedChat) State() jp.State { return jp.StatePlay }
func (p *S2CDisguisedChat) Bound() jp.Bound { return jp.S2C }

func (p *S2CEntityEvent) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CEntityEventID) }
func (p *S2CEntityEvent) State() jp.State { return jp.StatePlay }
func (p *S2CEntityEvent) Bound() jp.Bound { return jp.S2C }

func (p *S2CEntityPositionSync) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CEntityPositionSyncID) }
func (p *S2CEntityPositionSync) State() jp.State { return jp.StatePlay }
func (p *S2CEntityPositionSync) Bound() jp.Bound { return jp.S2C }

func (p *S2CExplode) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CExplodeID) }
func (p *S2CExplode) State() jp.State { return jp.StatePlay }
func (p *S2CExplode) Bound() jp.Bound { return jp.S2C }

func (p *S2CForgetLevelChunk) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CForgetLevelChunkID) }
func (p *S2CForgetLevelChunk) State() jp.State { return jp.StatePlay }
func (p *S2CForgetLevelChunk) Bound() jp.Bound { return jp.S2C }

func (p *S2CGameEvent) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CGameEventID) }
func (p *S2CGameEvent) State() jp.State { return jp.StatePlay }
func (p *S2CGameEvent) Bound() jp.Bound { return jp.S2C }

func (p *S2CGameTestHighlightPos) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CGameTestHighlightPosID)
}
func (p *S2CGameTestHighlightPos) State() jp.State { return jp.StatePlay }
func (p *S2CGameTestHighlightPos) Bound() jp.Bound { return jp.S2C }

func (p *S2CHurtAnimation) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CHurtAnimationID) }
func (p *S2CHurtAnimation) State() jp.State { return jp.StatePlay }
func (p *S2CHurtAnimation) Bound() jp.Bound { return jp.S2C }

func (p *S2CInitializeBorder) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CInitializeBorderID) }
func (p *S2CInitializeBorder) State() jp.State { return jp.StatePlay }
func (p *S2CInitializeBorder) Bound() jp.Bound { return jp.S2C }

func (p *S2CKeepAlivePlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CKeepAlivePlayID) }
func (p *S2CKeepAlivePlay) State() jp.State { return jp.StatePlay }
func (p *S2CKeepAlivePlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CLevelChunkWithLight) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CLevelChunkWithLightID)
}
func (p *S2CLevelChunkWithLight) State() jp.State { return jp.StatePlay }
func (p *S2CLevelChunkWithLight) Bound() jp.Bound { return jp.S2C }

func (p *S2CLevelEvent) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CLevelEventID) }
func (p *S2CLevelEvent) State() jp.State { return jp.StatePlay }
func (p *S2CLevelEvent) Bound() jp.Bound { return jp.S2C }

func (p *S2CLevelParticles) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CLevelParticlesID) }
func (p *S2CLevelParticles) State() jp.State { return jp.StatePlay }
func (p *S2CLevelParticles) Bound() jp.Bound { return jp.S2C }

func (p *S2CLightUpdate) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CLightUpdateID) }
func (p *S2CLightUpdate) State() jp.State { return jp.StatePlay }
func (p *S2CLightUpdate) Bound() jp.Bound { return jp.S2C }

func (p *S2CLogin) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CLoginID) }
func (p *S2CLogin) State() jp.State { return jp.StatePlay }
func (p *S2CLogin) Bound() jp.Bound { return jp.S2C }

func (p *S2CMapItemData) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CMapItemDataID) }
func (p *S2CMapItemData) State() jp.State { return jp.StatePlay }
func (p *S2CMapItemData) Bound() jp.Bound { return jp.S2C }

func (p *S2CMerchantOffers) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CMerchantOffersID) }
func (p *S2CMerchantOffers) State() jp.State { return jp.StatePlay }
func (p *S2CMerchantOffers) Bound() jp.Bound { return jp.S2C }

func (p *S2CMountScreenOpen) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CMountScreenOpenID) }
func (p *S2CMountScreenOpen) State() jp.State { return jp.StatePlay }
func (p *S2CMountScreenOpen) Bound() jp.Bound { return jp.S2C }

func (p *S2CMoveEntityPos) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CMoveEntityPosID) }
func (p *S2CMoveEntityPos) State() jp.State { return jp.StatePlay }
func (p *S2CMoveEntityPos) Bound() jp.Bound { return jp.S2C }

func (p *S2CMoveEntityPosRot) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CMoveEntityPosRotID) }
func (p *S2CMoveEntityPosRot) State() jp.State { return jp.StatePlay }
func (p *S2CMoveEntityPosRot) Bound() jp.Bound { return jp.S2C }

func (p *S2CMoveEntityRot) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CMoveEntityRotID) }
func (p *S2CMoveEntityRot) State() jp.State { return jp.StatePlay }
func (p *S2CMoveEntityRot) Bound() jp.Bound { return jp.S2C }

func (p *S2CMoveMinecartAlongTrack) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CMoveMinecartAlongTrackID)
}
func (p *S2CMoveMinecartAlongTrack) State() jp.State { return jp.StatePlay }
func (p *S2CMoveMinecartAlongTrack) Bound() jp.Bound { return jp.S2C }

func (p *S2CMoveVehicle) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CMoveVehicleID) }
func (p *S2CMoveVehicle) State() jp.State { return jp.StatePlay }
func (p *S2CMoveVehicle) Bound() jp.Bound { return jp.S2C }

func (p *S2COpenBook) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2COpenBookID) }
func (p *S2COpenBook) State() jp.State { return jp.StatePlay }
func (p *S2COpenBook) Bound() jp.Bound { return jp.S2C }

func (p *S2COpenScreen) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2COpenScreenID) }
func (p *S2COpenScreen) State() jp.State { return jp.StatePlay }
func (p *S2COpenScreen) Bound() jp.Bound { return jp.S2C }

func (p *S2COpenSignEditor) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2COpenSignEditorID) }
func (p *S2COpenSignEditor) State() jp.State { return jp.StatePlay }
func (p *S2COpenSignEditor) Bound() jp.Bound { return jp.S2C }

func (p *S2CPingPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPingPlayID) }
func (p *S2CPingPlay) State() jp.State { return jp.StatePlay }
func (p *S2CPingPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlaceGhostRecipe) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlaceGhostRecipeID) }
func (p *S2CPlaceGhostRecipe) State() jp.State { return jp.StatePlay }
func (p *S2CPlaceGhostRecipe) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlayerAbilities) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlayerAbilitiesID) }
func (p *S2CPlayerAbilities) State() jp.State { return jp.StatePlay }
func (p *S2CPlayerAbilities) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlayerChat) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlayerChatID) }
func (p *S2CPlayerChat) State() jp.State { return jp.StatePlay }
func (p *S2CPlayerChat) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlayerCombatEnd) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlayerCombatEndID) }
func (p *S2CPlayerCombatEnd) State() jp.State { return jp.StatePlay }
func (p *S2CPlayerCombatEnd) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlayerCombatEnter) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlayerCombatEnterID) }
func (p *S2CPlayerCombatEnter) State() jp.State { return jp.StatePlay }
func (p *S2CPlayerCombatEnter) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlayerCombatKill) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlayerCombatKillID) }
func (p *S2CPlayerCombatKill) State() jp.State { return jp.StatePlay }
func (p *S2CPlayerCombatKill) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlayerInfoRemove) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlayerInfoRemoveID) }
func (p *S2CPlayerInfoRemove) State() jp.State { return jp.StatePlay }
func (p *S2CPlayerInfoRemove) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlayerInfoUpdate) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlayerInfoUpdateID) }
func (p *S2CPlayerInfoUpdate) State() jp.State { return jp.StatePlay }
func (p *S2CPlayerInfoUpdate) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlayerLookAt) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlayerLookAtID) }
func (p *S2CPlayerLookAt) State() jp.State { return jp.StatePlay }
func (p *S2CPlayerLookAt) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlayerPosition) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlayerPositionID) }
func (p *S2CPlayerPosition) State() jp.State { return jp.StatePlay }
func (p *S2CPlayerPosition) Bound() jp.Bound { return jp.S2C }

func (p *S2CPlayerRotation) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPlayerRotationID) }
func (p *S2CPlayerRotation) State() jp.State { return jp.StatePlay }
func (p *S2CPlayerRotation) Bound() jp.Bound { return jp.S2C }

func (p *S2CPongResponsePlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPongResponsePlayID) }
func (p *S2CPongResponsePlay) State() jp.State { return jp.StatePlay }
func (p *S2CPongResponsePlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CProjectilePower) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CProjectilePowerID) }
func (p *S2CProjectilePower) State() jp.State { return jp.StatePlay }
func (p *S2CProjectilePower) Bound() jp.Bound { return jp.S2C }

func (p *S2CRecipeBookAdd) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CRecipeBookAddID) }
func (p *S2CRecipeBookAdd) State() jp.State { return jp.StatePlay }
func (p *S2CRecipeBookAdd) Bound() jp.Bound { return jp.S2C }

func (p *S2CRecipeBookRemove) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CRecipeBookRemoveID) }
func (p *S2CRecipeBookRemove) State() jp.State { return jp.StatePlay }
func (p *S2CRecipeBookRemove) Bound() jp.Bound { return jp.S2C }

func (p *S2CRecipeBookSettings) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CRecipeBookSettingsID) }
func (p *S2CRecipeBookSettings) State() jp.State { return jp.StatePlay }
func (p *S2CRecipeBookSettings) Bound() jp.Bound { return jp.S2C }

func (p *S2CRemoveEntities) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CRemoveEntitiesID) }
func (p *S2CRemoveEntities) State() jp.State { return jp.StatePlay }
func (p *S2CRemoveEntities) Bound() jp.Bound { return jp.S2C }

func (p *S2CRemoveMobEffect) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CRemoveMobEffectID) }
func (p *S2CRemoveMobEffect) State() jp.State { return jp.StatePlay }
func (p *S2CRemoveMobEffect) Bound() jp.Bound { return jp.S2C }

func (p *S2CResetScore) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CResetScoreID) }
func (p *S2CResetScore) State() jp.State { return jp.StatePlay }
func (p *S2CResetScore) Bound() jp.Bound { return jp.S2C }

func (p *S2CResourcePackPopPlay) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CResourcePackPopPlayID)
}
func (p *S2CResourcePackPopPlay) State() jp.State { return jp.StatePlay }
func (p *S2CResourcePackPopPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CResourcePackPushPlay) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CResourcePackPushPlayID)
}
func (p *S2CResourcePackPushPlay) State() jp.State { return jp.StatePlay }
func (p *S2CResourcePackPushPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CRespawn) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CRespawnID) }
func (p *S2CRespawn) State() jp.State { return jp.StatePlay }
func (p *S2CRespawn) Bound() jp.Bound { return jp.S2C }

func (p *S2CRotateHead) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CRotateHeadID) }
func (p *S2CRotateHead) State() jp.State { return jp.StatePlay }
func (p *S2CRotateHead) Bound() jp.Bound { return jp.S2C }

func (p *S2CSectionBlocksUpdate) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CSectionBlocksUpdateID)
}
func (p *S2CSectionBlocksUpdate) State() jp.State { return jp.StatePlay }
func (p *S2CSectionBlocksUpdate) Bound() jp.Bound { return jp.S2C }

func (p *S2CSelectAdvancementsTab) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CSelectAdvancementsTabID)
}
func (p *S2CSelectAdvancementsTab) State() jp.State { return jp.StatePlay }
func (p *S2CSelectAdvancementsTab) Bound() jp.Bound { return jp.S2C }

func (p *S2CServerData) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CServerDataID) }
func (p *S2CServerData) State() jp.State { return jp.StatePlay }
func (p *S2CServerData) Bound() jp.Bound { return jp.S2C }

func (p *S2CServerLinksPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CServerLinksPlayID) }
func (p *S2CServerLinksPlay) State() jp.State { return jp.StatePlay }
func (p *S2CServerLinksPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetActionBarText) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetActionBarTextID) }
func (p *S2CSetActionBarText) State() jp.State { return jp.StatePlay }
func (p *S2CSetActionBarText) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetBorderCenter) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetBorderCenterID) }
func (p *S2CSetBorderCenter) State() jp.State { return jp.StatePlay }
func (p *S2CSetBorderCenter) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetBorderLerpSize) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetBorderLerpSizeID) }
func (p *S2CSetBorderLerpSize) State() jp.State { return jp.StatePlay }
func (p *S2CSetBorderLerpSize) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetBorderSize) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetBorderSizeID) }
func (p *S2CSetBorderSize) State() jp.State { return jp.StatePlay }
func (p *S2CSetBorderSize) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetBorderWarningDelay) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CSetBorderWarningDelayID)
}
func (p *S2CSetBorderWarningDelay) State() jp.State { return jp.StatePlay }
func (p *S2CSetBorderWarningDelay) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetBorderWarningDistance) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CSetBorderWarningDistanceID)
}
func (p *S2CSetBorderWarningDistance) State() jp.State { return jp.StatePlay }
func (p *S2CSetBorderWarningDistance) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetCamera) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetCameraID) }
func (p *S2CSetCamera) State() jp.State { return jp.StatePlay }
func (p *S2CSetCamera) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetChunkCacheCenter) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CSetChunkCacheCenterID)
}
func (p *S2CSetChunkCacheCenter) State() jp.State { return jp.StatePlay }
func (p *S2CSetChunkCacheCenter) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetChunkCacheRadius) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CSetChunkCacheRadiusID)
}
func (p *S2CSetChunkCacheRadius) State() jp.State { return jp.StatePlay }
func (p *S2CSetChunkCacheRadius) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetCursorItem) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetCursorItemID) }
func (p *S2CSetCursorItem) State() jp.State { return jp.StatePlay }
func (p *S2CSetCursorItem) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetDefaultSpawnPosition) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CSetDefaultSpawnPositionID)
}
func (p *S2CSetDefaultSpawnPosition) State() jp.State { return jp.StatePlay }
func (p *S2CSetDefaultSpawnPosition) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetDisplayObjective) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CSetDisplayObjectiveID)
}
func (p *S2CSetDisplayObjective) State() jp.State { return jp.StatePlay }
func (p *S2CSetDisplayObjective) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetEntityData) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetEntityDataID) }
func (p *S2CSetEntityData) State() jp.State { return jp.StatePlay }
func (p *S2CSetEntityData) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetEntityLink) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetEntityLinkID) }
func (p *S2CSetEntityLink) State() jp.State { return jp.StatePlay }
func (p *S2CSetEntityLink) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetEntityMotion) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetEntityMotionID) }
func (p *S2CSetEntityMotion) State() jp.State { return jp.StatePlay }
func (p *S2CSetEntityMotion) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetEquipment) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetEquipmentID) }
func (p *S2CSetEquipment) State() jp.State { return jp.StatePlay }
func (p *S2CSetEquipment) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetExperience) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetExperienceID) }
func (p *S2CSetExperience) State() jp.State { return jp.StatePlay }
func (p *S2CSetExperience) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetHealth) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetHealthID) }
func (p *S2CSetHealth) State() jp.State { return jp.StatePlay }
func (p *S2CSetHealth) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetHeldSlot) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetHeldSlotID) }
func (p *S2CSetHeldSlot) State() jp.State { return jp.StatePlay }
func (p *S2CSetHeldSlot) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetObjective) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetObjectiveID) }
func (p *S2CSetObjective) State() jp.State { return jp.StatePlay }
func (p *S2CSetObjective) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetPassengers) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetPassengersID) }
func (p *S2CSetPassengers) State() jp.State { return jp.StatePlay }
func (p *S2CSetPassengers) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetPlayerInventory) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetPlayerInventoryID) }
func (p *S2CSetPlayerInventory) State() jp.State { return jp.StatePlay }
func (p *S2CSetPlayerInventory) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetPlayerTeam) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetPlayerTeamID) }
func (p *S2CSetPlayerTeam) State() jp.State { return jp.StatePlay }
func (p *S2CSetPlayerTeam) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetScore) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetScoreID) }
func (p *S2CSetScore) State() jp.State { return jp.StatePlay }
func (p *S2CSetScore) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetSimulationDistance) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CSetSimulationDistanceID)
}
func (p *S2CSetSimulationDistance) State() jp.State { return jp.StatePlay }
func (p *S2CSetSimulationDistance) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetSubtitleText) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetSubtitleTextID) }
func (p *S2CSetSubtitleText) State() jp.State { return jp.StatePlay }
func (p *S2CSetSubtitleText) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetTime) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetTimeID) }
func (p *S2CSetTime) State() jp.State { return jp.StatePlay }
func (p *S2CSetTime) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetTitleText) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetTitleTextID) }
func (p *S2CSetTitleText) State() jp.State { return jp.StatePlay }
func (p *S2CSetTitleText) Bound() jp.Bound { return jp.S2C }

func (p *S2CSetTitlesAnimation) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSetTitlesAnimationID) }
func (p *S2CSetTitlesAnimation) State() jp.State { return jp.StatePlay }
func (p *S2CSetTitlesAnimation) Bound() jp.Bound { return jp.S2C }

func (p *S2CShowDialogPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CShowDialogPlayID) }
func (p *S2CShowDialogPlay) State() jp.State { return jp.StatePlay }
func (p *S2CShowDialogPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CSound) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSoundID) }
func (p *S2CSound) State() jp.State { return jp.StatePlay }
func (p *S2CSound) Bound() jp.Bound { return jp.S2C }

func (p *S2CSoundEntity) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSoundEntityID) }
func (p *S2CSoundEntity) State() jp.State { return jp.StatePlay }
func (p *S2CSoundEntity) Bound() jp.Bound { return jp.S2C }

func (p *S2CStartConfiguration) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CStartConfigurationID) }
func (p *S2CStartConfiguration) State() jp.State { return jp.StatePlay }
func (p *S2CStartConfiguration) Bound() jp.Bound { return jp.S2C }

func (p *S2CStopSound) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CStopSoundID) }
func (p *S2CStopSound) State() jp.State { return jp.StatePlay }
func (p *S2CStopSound) Bound() jp.Bound { return jp.S2C }

func (p *S2CStoreCookiePlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CStoreCookiePlayID) }
func (p *S2CStoreCookiePlay) State() jp.State { return jp.StatePlay }
func (p *S2CStoreCookiePlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CSystemChat) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CSystemChatID) }
func (p *S2CSystemChat) State() jp.State { return jp.StatePlay }
func (p *S2CSystemChat) Bound() jp.Bound { return jp.S2C }

func (p *S2CTabList) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CTabListID) }
func (p *S2CTabList) State() jp.State { return jp.StatePlay }
func (p *S2CTabList) Bound() jp.Bound { return jp.S2C }

func (p *S2CTagQuery) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CTagQueryID) }
func (p *S2CTagQuery) State() jp.State { return jp.StatePlay }
func (p *S2CTagQuery) Bound() jp.Bound { return jp.S2C }

func (p *S2CTakeItemEntity) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CTakeItemEntityID) }
func (p *S2CTakeItemEntity) State() jp.State { return jp.StatePlay }
func (p *S2CTakeItemEntity) Bound() jp.Bound { return jp.S2C }

func (p *S2CTeleportEntity) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CTeleportEntityID) }
func (p *S2CTeleportEntity) State() jp.State { return jp.StatePlay }
func (p *S2CTeleportEntity) Bound() jp.Bound { return jp.S2C }

func (p *S2CTestInstanceBlockStatus) ID() ns.VarInt {
	return ns.VarInt(packet_ids.S2CTestInstanceBlockStatusID)
}
func (p *S2CTestInstanceBlockStatus) State() jp.State { return jp.StatePlay }
func (p *S2CTestInstanceBlockStatus) Bound() jp.Bound { return jp.S2C }

func (p *S2CTickingState) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CTickingStateID) }
func (p *S2CTickingState) State() jp.State { return jp.StatePlay }
func (p *S2CTickingState) Bound() jp.Bound { return jp.S2C }

func (p *S2CTickingStep) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CTickingStepID) }
func (p *S2CTickingStep) State() jp.State { return jp.StatePlay }
func (p *S2CTickingStep) Bound() jp.Bound { return jp.S2C }

func (p *S2CTransferPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CTransferPlayID) }
func (p *S2CTransferPlay) State() jp.State { return jp.StatePlay }
func (p *S2CTransferPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CUpdateAdvancements) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CUpdateAdvancementsID) }
func (p *S2CUpdateAdvancements) State() jp.State { return jp.StatePlay }
func (p *S2CUpdateAdvancements) Bound() jp.Bound { return jp.S2C }

func (p *S2CUpdateAttributes) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CUpdateAttributesID) }
func (p *S2CUpdateAttributes) State() jp.State { return jp.StatePlay }
func (p *S2CUpdateAttributes) Bound() jp.Bound { return jp.S2C }

func (p *S2CUpdateMobEffect) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CUpdateMobEffectID) }
func (p *S2CUpdateMobEffect) State() jp.State { return jp.StatePlay }
func (p *S2CUpdateMobEffect) Bound() jp.Bound { return jp.S2C }

func (p *S2CUpdateRecipes) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CUpdateRecipesID) }
func (p *S2CUpdateRecipes) State() jp.State { return jp.StatePlay }
func (p *S2CUpdateRecipes) Bound() jp.Bound { return jp.S2C }

func (p *S2CUpdateTagsPlay) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CUpdateTagsPlayID) }
func (p *S2CUpdateTagsPlay) State() jp.State { return jp.StatePlay }
func (p *S2CUpdateTagsPlay) Bound() jp.Bound { return jp.S2C }

func (p *S2CWaypoint) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CWaypointID) }
func (p *S2CWaypoint) State() jp.State { return jp.StatePlay }
func (p *S2CWaypoint) Bound() jp.Bound { return jp.S2C }

func (p *C2SPingRequestStatus) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SPingRequestStatusID) }
func (p *C2SPingRequestStatus) State() jp.State { return jp.StateStatus }
func (p *C2SPingRequestStatus) Bound() jp.Bound { return jp.C2S }

func (p *C2SStatusRequest) ID() ns.VarInt   { return ns.VarInt(packet_ids.C2SStatusRequestID) }
func (p *C2SStatusRequest) State() jp.State { return jp.StateStatus }
func (p *C2SStatusRequest) Bound() jp.Bound { return jp.C2S }

func (p *S2CPongResponseStatus) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CPongResponseStatusID) }
func (p *S2CPongResponseStatus) State() jp.State { return jp.StateStatus }
func (p *S2CPongResponseStatus) Bound() jp.Bound { return jp.S2C }

func (p *S2CStatusResponse) ID() ns.VarInt   { return ns.VarInt(packet_ids.S2CStatusResponseID) }
func (p *S2CStatusResponse) State() jp.State { return jp.StateStatus }
func (p *S2CStatusResponse) Bound() jp.Bound { return jp.S2C }
