package packets

import (
	ns "github.com/zeozeozeo/minego/internal/protocol/java_protocol/net_structures"
)

// S2CLoginDisconnectLogin represents "Disconnect (login)".
// Unlike play/config disconnect (NBT), login uses JSON (ByteBufCodecs.lenientJson).
//
// https://minecraft.wiki/w/Java_Edition_protocol/Packets#Disconnect_(Login)
type S2CLoginDisconnectLogin struct {
	// The reason why the player was disconnected.
	Reason ns.TextComponent
}

func (p *S2CLoginDisconnectLogin) Read(buf *ns.PacketBuffer) error {
	var err error
	p.Reason, err = buf.ReadJsonTextComponent()
	return err
}

func (p *S2CLoginDisconnectLogin) Write(buf *ns.PacketBuffer) error {
	return buf.WriteJsonTextComponent(p.Reason)
}

// S2CHello represents "Encryption Request".
//
// See protocol encryption for details.
//
// https://minecraft.wiki/w/Java_Edition_protocol/Packets#Encryption_Request
type S2CHello struct {
	// Always empty when sent by the vanilla server.
	ServerId ns.String
	// The server's public key, in bytes.
	PublicKey ns.ByteArray
	// A sequence of random bytes generated by the server.
	VerifyToken ns.ByteArray
	// Whether the client should attempt to authenticate through mojang servers.
	ShouldAuthenticate ns.Boolean
}

func (p *S2CHello) Read(buf *ns.PacketBuffer) error {
	var err error
	if p.ServerId, err = buf.ReadString(20); err != nil {
		return err
	}
	if p.PublicKey, err = buf.ReadByteArray(256); err != nil {
		return err
	}
	if p.VerifyToken, err = buf.ReadByteArray(256); err != nil {
		return err
	}
	p.ShouldAuthenticate, err = buf.ReadBool()
	return err
}

func (p *S2CHello) Write(buf *ns.PacketBuffer) error {
	if err := buf.WriteString(p.ServerId); err != nil {
		return err
	}
	if err := buf.WriteByteArray(p.PublicKey); err != nil {
		return err
	}
	if err := buf.WriteByteArray(p.VerifyToken); err != nil {
		return err
	}
	return buf.WriteBool(p.ShouldAuthenticate)
}

// GameProfileProperty represents a single property in a GameProfile.
type GameProfileProperty struct {
	Name      ns.String
	Value     ns.String
	Signature ns.PrefixedOptional[ns.String]
}

// GameProfile represents a player's game profile.
type GameProfile struct {
	UUID       ns.UUID
	Name       ns.String
	Properties []GameProfileProperty
}

// S2CLoginFinished represents "Login Success".
//
// https://minecraft.wiki/w/Java_Edition_protocol/Packets#Login_Success
type S2CLoginFinished struct {
	Profile GameProfile
	// SessionId is the player's session UUID (added in 26.2).
	SessionId ns.UUID
}

func (p *S2CLoginFinished) Read(buf *ns.PacketBuffer) error {
	var err error
	if p.Profile.UUID, err = buf.ReadUUID(); err != nil {
		return err
	}
	if p.Profile.Name, err = buf.ReadString(16); err != nil {
		return err
	}
	count, err := buf.ReadVarInt()
	if err != nil {
		return err
	}
	p.Profile.Properties = make([]GameProfileProperty, count)
	for i := range p.Profile.Properties {
		if p.Profile.Properties[i].Name, err = buf.ReadString(64); err != nil {
			return err
		}
		if p.Profile.Properties[i].Value, err = buf.ReadString(32767); err != nil {
			return err
		}
		if err = p.Profile.Properties[i].Signature.DecodeWith(buf, func(b *ns.PacketBuffer) (ns.String, error) {
			return b.ReadString(1024)
		}); err != nil {
			return err
		}
	}
	p.SessionId, err = buf.ReadUUID()
	return err
}

func (p *S2CLoginFinished) Write(buf *ns.PacketBuffer) error {
	if err := buf.WriteUUID(p.Profile.UUID); err != nil {
		return err
	}
	if err := buf.WriteString(p.Profile.Name); err != nil {
		return err
	}
	if err := buf.WriteVarInt(ns.VarInt(len(p.Profile.Properties))); err != nil {
		return err
	}
	for _, prop := range p.Profile.Properties {
		if err := buf.WriteString(prop.Name); err != nil {
			return err
		}
		if err := buf.WriteString(prop.Value); err != nil {
			return err
		}
		if err := prop.Signature.EncodeWith(buf, func(b *ns.PacketBuffer, v ns.String) error {
			return b.WriteString(v)
		}); err != nil {
			return err
		}
	}
	return buf.WriteUUID(p.SessionId)
}

// S2CLoginCompression represents "Set Compression".
//
// Enables compression. If compression is enabled, all following packets are
// encoded in the compressed packet format. Negative values will disable compression.
//
// https://minecraft.wiki/w/Java_Edition_protocol/Packets#Set_Compression
type S2CLoginCompression struct {
	// Maximum size of a packet before it is compressed.
	Threshold ns.VarInt
}

func (p *S2CLoginCompression) Read(buf *ns.PacketBuffer) error {
	var err error
	p.Threshold, err = buf.ReadVarInt()
	return err
}

func (p *S2CLoginCompression) Write(buf *ns.PacketBuffer) error {
	return buf.WriteVarInt(p.Threshold)
}

// S2CCustomQuery represents "Login Plugin Request".
//
// Used to implement a custom handshaking flow together with Login Plugin Response.
//
// https://minecraft.wiki/w/Java_Edition_protocol/Packets#Login_Plugin_Request
type S2CCustomQuery struct {
	// Generated by the server - should be unique to the connection.
	MessageId ns.VarInt
	// Name of the plugin channel used to send the data.
	Channel ns.Identifier
	// Any data, depending on the channel.
	Data ns.ByteArray
}

func (p *S2CCustomQuery) Read(buf *ns.PacketBuffer) error {
	var err error
	if p.MessageId, err = buf.ReadVarInt(); err != nil {
		return err
	}
	if p.Channel, err = buf.ReadIdentifier(); err != nil {
		return err
	}
	p.Data, err = buf.ReadByteArray(1048576)
	return err
}

func (p *S2CCustomQuery) Write(buf *ns.PacketBuffer) error {
	if err := buf.WriteVarInt(p.MessageId); err != nil {
		return err
	}
	if err := buf.WriteIdentifier(p.Channel); err != nil {
		return err
	}
	return buf.WriteByteArray(p.Data)
}

// S2CCookieRequestLogin represents "Cookie Request (login)".
//
// Requests a cookie that was previously stored.
//
// https://minecraft.wiki/w/Java_Edition_protocol/Packets#Cookie_Request_(Login)
type S2CCookieRequestLogin struct {
	// The identifier of the cookie.
	Key ns.Identifier
}

func (p *S2CCookieRequestLogin) Read(buf *ns.PacketBuffer) error {
	var err error
	p.Key, err = buf.ReadIdentifier()
	return err
}

func (p *S2CCookieRequestLogin) Write(buf *ns.PacketBuffer) error {
	return buf.WriteIdentifier(p.Key)
}
